package com.tripwise.model;

import lombok.Data;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;
import java.time.LocalDateTime;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "trip_plan_sessions")
public class TripPlanSession {

    @Id
    private String id;

    @Field("profileId")
    private String profileId;

    @Field("createdAt")
    private LocalDateTime createdAt;

    @Field("updatedAt")
    private LocalDateTime updatedAt;

    @Field("currentStep")
    private PlanningStep currentStep;

    @Field("destination")
    private String destination;

    // STEP 1: Overview Data (Generated by AI)
    @Field("destinationOverview")
    private String destinationOverview;

    // STEP 4: Finalized master plan JSON
    @Field("masterPlan")
    private String masterPlan;

    @Field("estimatedBudgetRange")
    private String estimatedBudgetRange;

    // STEP 2: Hotel Selection
    @Field("suggestedHotels")
    private String suggestedHotelsJson; // Storing the raw AI suggestion JSON

    @Field("selectedHotel")
    private HotelOption selectedHotel;

    // STEP 3: Transport Choice
    @Field("suggestedTransport")
    private String suggestedTransportJson; // Storing the raw AI suggestion JSON

    @Field("finalizedTransportChoice")
    private TransportOption finalizedTransportChoice;

    public enum PlanningStep {
        INIT,
        HOTEL_SELECTION,
        TRANSPORT_SELECTION,
        FINALIZED
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class HotelOption {
        private String name;
        private String address;
        private String costPerNight;
        private String reason;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class TransportOption {
        private String mode; // e.g., "Metro", "Uber", "Hotel Shuttle"
        private String cost;
        private String duration;
        private String details;
    }
}
